import os
import sys
from functools import wraps
from flask import session, redirect, url_for, flash

if getattr(sys, "frozen", False):
    _base = os.path.dirname(sys.executable)
else:
    _base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DATABASE_URL = os.environ.get("DATABASE_URL", "")
DB_PATH = os.environ.get("DB_PATH") or os.path.join(_base, "controle_loteamentos.db")
RECIBOS_DIR = os.environ.get("RECIBOS_DIR") or os.path.join(_base, "recibos")

os.makedirs(RECIBOS_DIR, exist_ok=True)

USING_PG = bool(DATABASE_URL)


if USING_PG:
    import psycopg2
    import psycopg2.extras

    class _PgConnection:
        def __init__(self, conn):
            self._conn = conn

        def execute(self, sql, params=None):
            cur = self._conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
            cur.execute(sql.replace("?", "%s"), params or ())
            return cur

        def executescript(self, sql):
            cur = self._conn.cursor()
            for stmt in sql.split(";"):
                s = stmt.strip()
                if s:
                    cur.execute(s)
            cur.close()

        def commit(self):
            try:
                self._conn.commit()
            except Exception:
                pass

        def rollback(self):
            try:
                self._conn.rollback()
            except Exception:
                pass

        def close(self):
            try:
                self._conn.close()
            except Exception:
                pass

        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc_val, exc_tb):
            if exc_type is None:
                try:
                    self._conn.commit()
                except Exception:
                    self._conn.rollback()
            else:
                try:
                    self._conn.rollback()
                except Exception:
                    pass
            try:
                self._conn.close()
            except Exception:
                pass

    def get_db():
        conn = psycopg2.connect(DATABASE_URL)
        conn.autocommit = True
        return _PgConnection(conn)

else:
    import sqlite3

    def get_db():
        conn = sqlite3.connect(DB_PATH, timeout=20)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA busy_timeout=5000")
        return conn


def _init_pg(conn):
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS usuarios (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS formas_pagamento (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL UNIQUE,
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS pessoas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL, cpf TEXT DEFAULT '', rg TEXT DEFAULT '',
            contato TEXT DEFAULT '', endereco TEXT DEFAULT '',
            observacao TEXT DEFAULT '', referencia_marcacao TEXT DEFAULT '',
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS loteamentos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL, endereco TEXT DEFAULT '',
            qtd_quadras INTEGER DEFAULT 0, qtd_lotes INTEGER DEFAULT 0,
            lat DOUBLE PRECISION, lng DOUBLE PRECISION,
            ativo INTEGER DEFAULT 1,
            croqui_data TEXT DEFAULT '{}',
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS usuario_loteamentos (
            usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
            loteamento_id INTEGER NOT NULL REFERENCES loteamentos(id) ON DELETE CASCADE,
            UNIQUE(usuario_id, loteamento_id)
        );
        CREATE TABLE IF NOT EXISTS permissoes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
            modulo TEXT NOT NULL,
            UNIQUE(usuario_id, modulo)
        );
        CREATE TABLE IF NOT EXISTS quadras (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            loteamento_id INTEGER NOT NULL REFERENCES loteamentos(id) ON DELETE CASCADE,
            identificacao TEXT NOT NULL, qtd_lotes INTEGER DEFAULT 0,
            rua_norte TEXT DEFAULT '', rua_sul TEXT DEFAULT '',
            rua_leste TEXT DEFAULT '', rua_oeste TEXT DEFAULT '',
            polygon_coords TEXT DEFAULT '[]',
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS lotes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            quadra_id INTEGER NOT NULL REFERENCES quadras(id) ON DELETE CASCADE,
            numero TEXT DEFAULT '',
            tamanho_frente DOUBLE PRECISION DEFAULT 0,
            tamanho_fundo DOUBLE PRECISION DEFAULT 0,
            tamanho_esquerda DOUBLE PRECISION DEFAULT 0,
            tamanho_direita DOUBLE PRECISION DEFAULT 0,
            dono_nome TEXT DEFAULT '', dono_cpf TEXT DEFAULT '', dono_contato TEXT DEFAULT '',
            lotes_limitrofes TEXT DEFAULT '[]',
            status TEXT DEFAULT 'disponivel',
            polygon_coords TEXT DEFAULT '[]',
            dono_pessoa_id INTEGER REFERENCES pessoas(id),
            vendedor_pessoa_id INTEGER REFERENCES pessoas(id),
            comprador_pessoa_id INTEGER REFERENCES pessoas(id),
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS permutas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data DATE NOT NULL DEFAULT CURRENT_DATE,
            dono_anterior_nome TEXT NOT NULL, dono_anterior_cpf TEXT DEFAULT '',
            dono_posterior_nome TEXT NOT NULL, dono_posterior_cpf TEXT DEFAULT '',
            observacao TEXT DEFAULT '', recibo_pdf TEXT DEFAULT '',
            dono_anterior_pessoa_id INTEGER REFERENCES pessoas(id),
            dono_posterior_pessoa_id INTEGER REFERENCES pessoas(id),
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS permuta_lotes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            permuta_id INTEGER NOT NULL REFERENCES permutas(id) ON DELETE CASCADE,
            lote_id INTEGER NOT NULL REFERENCES lotes(id) ON DELETE CASCADE,
            UNIQUE(permuta_id, lote_id)
        );
        CREATE TABLE IF NOT EXISTS vendas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data DATE NOT NULL DEFAULT CURRENT_DATE,
            lote_id INTEGER NOT NULL REFERENCES lotes(id),
            vendedor_nome TEXT NOT NULL, vendedor_cpf TEXT DEFAULT '', vendedor_contato TEXT DEFAULT '',
            comprador_nome TEXT NOT NULL, comprador_cpf TEXT DEFAULT '', comprador_contato TEXT DEFAULT '',
            valor_total DOUBLE PRECISION DEFAULT 0,
            forma_pagamento_id INTEGER REFERENCES formas_pagamento(id),
            numero_parcelas INTEGER DEFAULT 1,
            observacao TEXT DEFAULT '', recibo_pdf TEXT DEFAULT '',
            vendedor_pessoa_id INTEGER REFERENCES pessoas(id),
            comprador_pessoa_id INTEGER REFERENCES pessoas(id),
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS pagamentos_venda (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            venda_id INTEGER NOT NULL REFERENCES vendas(id) ON DELETE CASCADE,
            numero_parcela INTEGER DEFAULT 1,
            data_vencimento DATE DEFAULT NULL,
            data_pagamento DATE DEFAULT NULL,
            valor DOUBLE PRECISION DEFAULT 0,
            pago INTEGER DEFAULT 0,
            recibo_pdf TEXT DEFAULT '',
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS pontos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            loteamento_id INTEGER NOT NULL REFERENCES loteamentos(id) ON DELETE CASCADE,
            lat DOUBLE PRECISION NOT NULL, lng DOUBLE PRECISION NOT NULL,
            nome TEXT NOT NULL DEFAULT '', tipo TEXT NOT NULL DEFAULT 'ponto',
            cor TEXT NOT NULL DEFAULT '#2196f3', descricao TEXT DEFAULT '',
            icone TEXT DEFAULT '\U0001f4cd',
            criado_em TIMESTAMP NOT NULL DEFAULT NOW()
        );
    """)


def _init_sqlite(conn):
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS usuarios (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS permissoes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
            modulo TEXT NOT NULL,
            UNIQUE(usuario_id, modulo)
        );
        CREATE TABLE IF NOT EXISTS loteamentos (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT NOT NULL,
            endereco TEXT DEFAULT '',
            qtd_quadras INTEGER DEFAULT 0,
            qtd_lotes INTEGER DEFAULT 0,
            lat REAL, lng REAL,
            ativo INTEGER DEFAULT 1,
            croqui_data TEXT DEFAULT '{}',
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS quadras (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            loteamento_id INTEGER NOT NULL REFERENCES loteamentos(id) ON DELETE CASCADE,
            identificacao TEXT NOT NULL,
            qtd_lotes INTEGER DEFAULT 0,
            rua_norte TEXT DEFAULT '', rua_sul TEXT DEFAULT '',
            rua_leste TEXT DEFAULT '', rua_oeste TEXT DEFAULT '',
            polygon_coords TEXT DEFAULT '[]',
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS lotes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            quadra_id INTEGER NOT NULL REFERENCES quadras(id) ON DELETE CASCADE,
            numero TEXT DEFAULT '',
            tamanho_frente REAL DEFAULT 0, tamanho_fundo REAL DEFAULT 0,
            tamanho_esquerda REAL DEFAULT 0, tamanho_direita REAL DEFAULT 0,
            dono_nome TEXT DEFAULT '', dono_cpf TEXT DEFAULT '', dono_contato TEXT DEFAULT '',
            lotes_limitrofes TEXT DEFAULT '[]',
            status TEXT DEFAULT 'disponivel',
            polygon_coords TEXT DEFAULT '[]',
            dono_pessoa_id INTEGER REFERENCES pessoas(id),
            vendedor_pessoa_id INTEGER REFERENCES pessoas(id),
            comprador_pessoa_id INTEGER REFERENCES pessoas(id),
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS formas_pagamento (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT NOT NULL UNIQUE,
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS permutas (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            data TEXT NOT NULL DEFAULT (date('now','localtime')),
            dono_anterior_nome TEXT NOT NULL, dono_anterior_cpf TEXT DEFAULT '',
            dono_posterior_nome TEXT NOT NULL, dono_posterior_cpf TEXT DEFAULT '',
            observacao TEXT DEFAULT '', recibo_pdf TEXT DEFAULT '',
            dono_anterior_pessoa_id INTEGER REFERENCES pessoas(id),
            dono_posterior_pessoa_id INTEGER REFERENCES pessoas(id),
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS permuta_lotes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            permuta_id INTEGER NOT NULL REFERENCES permutas(id) ON DELETE CASCADE,
            lote_id INTEGER NOT NULL REFERENCES lotes(id) ON DELETE CASCADE,
            UNIQUE(permuta_id, lote_id)
        );
        CREATE TABLE IF NOT EXISTS vendas (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            data TEXT NOT NULL DEFAULT (date('now','localtime')),
            lote_id INTEGER NOT NULL REFERENCES lotes(id),
            vendedor_nome TEXT NOT NULL, vendedor_cpf TEXT DEFAULT '', vendedor_contato TEXT DEFAULT '',
            comprador_nome TEXT NOT NULL, comprador_cpf TEXT DEFAULT '', comprador_contato TEXT DEFAULT '',
            valor_total REAL DEFAULT 0,
            forma_pagamento_id INTEGER REFERENCES formas_pagamento(id),
            numero_parcelas INTEGER DEFAULT 1,
            observacao TEXT DEFAULT '', recibo_pdf TEXT DEFAULT '',
            vendedor_pessoa_id INTEGER REFERENCES pessoas(id),
            comprador_pessoa_id INTEGER REFERENCES pessoas(id),
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS pagamentos_venda (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            venda_id INTEGER NOT NULL REFERENCES vendas(id) ON DELETE CASCADE,
            numero_parcela INTEGER DEFAULT 1,
            data_vencimento TEXT DEFAULT '', data_pagamento TEXT DEFAULT '',
            valor REAL DEFAULT 0, pago INTEGER DEFAULT 0,
            recibo_pdf TEXT DEFAULT '',
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS usuario_loteamentos (
            usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
            loteamento_id INTEGER NOT NULL REFERENCES loteamentos(id) ON DELETE CASCADE,
            UNIQUE(usuario_id, loteamento_id)
        );
        CREATE TABLE IF NOT EXISTS pessoas (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT NOT NULL, cpf TEXT DEFAULT '', rg TEXT DEFAULT '',
            contato TEXT DEFAULT '', endereco TEXT DEFAULT '',
            observacao TEXT DEFAULT '', referencia_marcacao TEXT DEFAULT '',
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
        CREATE TABLE IF NOT EXISTS pontos (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            loteamento_id INTEGER NOT NULL REFERENCES loteamentos(id) ON DELETE CASCADE,
            lat REAL NOT NULL, lng REAL NOT NULL,
            nome TEXT NOT NULL DEFAULT '', tipo TEXT NOT NULL DEFAULT 'ponto',
            cor TEXT NOT NULL DEFAULT '#2196f3', descricao TEXT DEFAULT '',
            icone TEXT DEFAULT '\U0001f4cd',
            criado_em TEXT NOT NULL DEFAULT (datetime('now','localtime'))
        );
    """)



def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if "usuario_id" not in session:
            return redirect(url_for("login"))
        return f(*args, **kwargs)
    return decorated


def permissao_required(modulo):
    def decorator(f):
        @wraps(f)
        def decorated(*args, **kwargs):
            if modulo not in session.get("permissoes", []):
                flash("Acesso negado.")
                return redirect(url_for("index"))
            return f(*args, **kwargs)
        return decorated
    return decorator
